### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by RIPJumPiesS** [DupeQOLmod/SkyblockextrasQOL#1]
Crashes my game and gives an error message.
![image](https://user-images.githubusercontent.com/66848434/159176167-18e5b09f-6942-460f-b069-7efbadf8354e.png)

**Comment by DupeQOLmod** [comment]
Hey! Thank's for report. Can you send me please photo your mods folder?
Because any mods don't like this mod

**Comment by RIPJumPiesS** [comment]
> Hey! Thank's for report. Can you send me please photo your mods folder? Because any mods don't like this mod

![image](https://user-images.githubusercontent.com/66848434/159178974-2514b578-664c-4c69-a2a9-436fa9d1b5fa.png)
This is the only thing in my mods folder

**Comment by RIPJumPiesS** [comment]
![image](https://user-images.githubusercontent.com/66848434/159179031-0fe34abe-6b15-4481-be0c-dfa8eecb8aea.png)
This is in forge when I launch forge tho i dont know what it is

**Comment by DupeQOLmod** [comment]
Go Options control and found it

**Comment by RIPJumPiesS** [comment]
> Go Options control and found it

?? What do you mean

**Comment by RIPJumPiesS** [comment]
Theres nothing new in controls with or without the mod

**Comment by RIPJumPiesS** [comment]
![image](https://user-images.githubusercontent.com/66848434/159179193-82025057-1955-49d2-8d21-4db9a61a42cf.png)
![image](https://user-images.githubusercontent.com/66848434/159179199-250cec55-4c43-40d0-83a8-afec660e9524.png)

**Comment by RIPJumPiesS** [comment]
This image is when i launch with the minion mod which doesnt let me open GUI's in game
